---
- hosts: localhost
  gather_facts: no
  vars:
    vcenter_server: "192.168.101.254"
    vcenter_user: "administrator@vsphere.local"
    vcenter_pass: "P@ssw0rd"
    datacenter_name: "Datacenter"
    cluster_name: "DevOps"
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: VM-Centos-01
      template: CentOS-Template
      datacenter: "{{ datacenter_name }}"
      folder: /{{ datacenter_name }}/vm
      cluster: "{{ cluster_name }}"
      datastore: "DevOPS-DS01"
      networks:
      - name: VM Network
        type: dhcp
        gateway: 192.168.101.12
        dns_servers: 192.168.100.5
      customization:
        hostname: "192.168.101.251"
        dns_servers:
        - 192.168.100.5
        - 8.8.8.8
      state: poweredon
      wait_for_ip_address: yes
    delegate_to: localhost