---
- hosts: worker
  vars_files:
  - ../env_variables
  tasks:
  - name: Copying token to worker nodes
    copy: src=/root/{{ token_file }} dest=/root/join_token

  - name: Joining worker nodes with kubernetes master
    shell: |
     kubeadm reset -f
     cat /root/join_token | tail -2 > out.sh
     sh out.sh
