// ID identifying the cluster to create. Use your username so that resources created can be tracked back to you.
cluster_id = "kube"

// Domain of the cluster. This should be "${cluster_id}.${base_domain}".
cluster_domain = "kube.sandz2.com.ph"

// Base domain from which the cluster domain is a subdomain.
base_domain = "sandz2.com.ph"

// Name of the vSphere server. The dev cluster is on "vcsa.vmware.devcluster.openshift.com".
vsphere_server = "Vcenterdevops.sandz.com.ph"

// User on the vSphere server.
vsphere_user = "administrator@vsphere.local"

// Password of the user on the vSphere server.
vsphere_password = "P@ssw0rd"

// Name of the vSphere cluster. The dev cluster is "devel".
vsphere_cluster = "devops"

// Name of the vSphere data center. The dev cluster is "dc1".
vsphere_datacenter = "Datacenter"

// Name of the vSphere data store to use for the VMs. The dev cluster uses "nvme-ds1".
vsphere_datastore = "DevOps"

// Name of the VM template to clone to create VMs for the cluster. The dev cluster has a template named "rhcos-latest".
vm_template = "rhcos-4.3.0"

// The machine_cidr where IP addresses will be assigned for cluster nodes.
// Additionally, IPAM will assign IPs based on the network ID. 
machine_cidr = "192.168.101.100/30"

vm_network = "No VLAN"

// The number of control plane VMs to create. Default is 3.
control_plane_count = 3

// The number of compute VMs to create. Default is 3.
compute_count = 1

// URL of the bootstrap ignition. This needs to be publicly accessible so that the bootstrap machine can pull the ignition.
bootstrap_ignition_url = "http://192.168.101.22/bootstrap.ign"

// Ignition config for the control plane machines. You should copy the contents of the master.ign generated by the installer.
control_plane_ignition = <<END_OF_MASTER_IGNITION
{"ignition":{"config":{"append":[{"source":"https://api-int.kube.sandz2.com.ph:22623/config/master","verification":{}}]},"security":{"tls":{"certificateAuthorities":[{"source":"data:text/plain;charset=utf-8;base64,LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFRENDQWZpZ0F3SUJBZ0lJWTVqV3dKb3oyUk13RFFZSktvWklodmNOQVFFTEJRQXdKakVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1SQXdEZ1lEVlFRREV3ZHliMjkwTFdOaE1CNFhEVEl3TURJeE5EQTVNakUxTlZvWApEVE13TURJeE1UQTVNakUxTlZvd0pqRVNNQkFHQTFVRUN4TUpiM0JsYm5Ob2FXWjBNUkF3RGdZRFZRUURFd2R5CmIyOTBMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFzT3pZT2g2QXo2MDgKQUg3Z2IrbExBSkF4UVlIckdZcnp3ZlVCajRxNnYwYndZNGQxd1BwV3VSdkpLWGRTNmh3UjhsMDVhYUlwWDRqcApFeUUwWmlHWFFWQVR4cTBtL3RGZEtlQjQxV0hHM1MwaEV6K1Y2N0cxdUxZZENMZHpSOWdxaXFXYlZsMnJQb090ClMzQnBSbitVdWQxeW9Gand1SXQzelhIS1VMbHIvaFM0UDNGWFZTOVZ6YnZOVjZDZkc1OG44NzA0bGxjb1lSeVEKcTZNWkhZSjRDc1d5Sk9aK2Q5NXp5NlFiaENBdU0rMm5ZQ1IwWS94VjlZdWN1UkpQZTNvMnFZRTJ6VThKbkZOUwpOTFJnbEgrVjhpQTFyQ21RTHJubTJ0WlNmcDRma3pyd1B3YkNFV2dhQWY2NzFnVlFhOXQyd0JmblRQL1dqZ0JYClUxSXYveTBuR1FJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBcVF3RHdZRFZSMFRBUUgvQkFVd0F3RUIKL3pBZEJnTlZIUTRFRmdRVXJCTVc2VEhKTGVVZnA0MVJFd3RBeDRzSjRIb3dEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQUhwbFlkVUJaMjRoRFByRWRxRXExbmVQUDhOSkVQRnJOdGVnSE9nbk96RGJ3WlZaRXFmV3JaOGgvL09aCi9JdDl5SWdNc2haYUVJUFUzcVdMN2tmZjJMWDlBTGhYemRrNjFGR3NOM0x4N295bkpwbm9HWTlWWWl2SkJTbXIKRVplb3g2UU5JUHV1OWtsc1FETC9udU5YTDJMS0lQYnlaMStlSS9qTDV3UjBjc2M1WnlTZWNwdzVQc0xGVnRYZQpoYzRHeFRWWlY0UW5yZkp5UCttNVBqZ1BYdE15ejd2RWdtMTlSUlMrMHlFSmVDVmVnR0tPSGwvVlJKbFFibzF1CkpHMnRkU3hPTHYzTm11cUgvV1dlVTlSUUd4QUZxNmhQUDZvUVFQeXhtYmxBWHh2NzlVYmJiK2xyZDArdFJ3bnQKWkhxeGFBbnhUVm4wQUE3ZzVNWW9SM3ZsaFVRPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==","verification":{}}]}},"timeouts":{},"version":"2.2.0"},"networkd":{},"passwd":{},"storage":{},"systemd":{}}
END_OF_MASTER_IGNITION

// Ignition config for the compute machines. You should copy the contents of the worker.ign generated by the installer.
compute_ignition = <<END_OF_WORKER_IGNITION
{"ignition":{"config":{"append":[{"source":"https://api-int.kube.sandz2.com.ph:22623/config/worker","verification":{}}]},"security":{"tls":{"certificateAuthorities":[{"source":"data:text/plain;charset=utf-8;base64,LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFRENDQWZpZ0F3SUJBZ0lJWTVqV3dKb3oyUk13RFFZSktvWklodmNOQVFFTEJRQXdKakVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1SQXdEZ1lEVlFRREV3ZHliMjkwTFdOaE1CNFhEVEl3TURJeE5EQTVNakUxTlZvWApEVE13TURJeE1UQTVNakUxTlZvd0pqRVNNQkFHQTFVRUN4TUpiM0JsYm5Ob2FXWjBNUkF3RGdZRFZRUURFd2R5CmIyOTBMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFzT3pZT2g2QXo2MDgKQUg3Z2IrbExBSkF4UVlIckdZcnp3ZlVCajRxNnYwYndZNGQxd1BwV3VSdkpLWGRTNmh3UjhsMDVhYUlwWDRqcApFeUUwWmlHWFFWQVR4cTBtL3RGZEtlQjQxV0hHM1MwaEV6K1Y2N0cxdUxZZENMZHpSOWdxaXFXYlZsMnJQb090ClMzQnBSbitVdWQxeW9Gand1SXQzelhIS1VMbHIvaFM0UDNGWFZTOVZ6YnZOVjZDZkc1OG44NzA0bGxjb1lSeVEKcTZNWkhZSjRDc1d5Sk9aK2Q5NXp5NlFiaENBdU0rMm5ZQ1IwWS94VjlZdWN1UkpQZTNvMnFZRTJ6VThKbkZOUwpOTFJnbEgrVjhpQTFyQ21RTHJubTJ0WlNmcDRma3pyd1B3YkNFV2dhQWY2NzFnVlFhOXQyd0JmblRQL1dqZ0JYClUxSXYveTBuR1FJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBcVF3RHdZRFZSMFRBUUgvQkFVd0F3RUIKL3pBZEJnTlZIUTRFRmdRVXJCTVc2VEhKTGVVZnA0MVJFd3RBeDRzSjRIb3dEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQUhwbFlkVUJaMjRoRFByRWRxRXExbmVQUDhOSkVQRnJOdGVnSE9nbk96RGJ3WlZaRXFmV3JaOGgvL09aCi9JdDl5SWdNc2haYUVJUFUzcVdMN2tmZjJMWDlBTGhYemRrNjFGR3NOM0x4N295bkpwbm9HWTlWWWl2SkJTbXIKRVplb3g2UU5JUHV1OWtsc1FETC9udU5YTDJMS0lQYnlaMStlSS9qTDV3UjBjc2M1WnlTZWNwdzVQc0xGVnRYZQpoYzRHeFRWWlY0UW5yZkp5UCttNVBqZ1BYdE15ejd2RWdtMTlSUlMrMHlFSmVDVmVnR0tPSGwvVlJKbFFibzF1CkpHMnRkU3hPTHYzTm11cUgvV1dlVTlSUUd4QUZxNmhQUDZvUVFQeXhtYmxBWHh2NzlVYmJiK2xyZDArdFJ3bnQKWkhxeGFBbnhUVm4wQUE3ZzVNWW9SM3ZsaFVRPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==","verification":{}}]}},"timeouts":{},"version":"2.2.0"},"networkd":{},"passwd":{},"storage":{},"systemd":{}}
END_OF_WORKER_IGNITION

// Set ipam and ipam_token if you want to use the IPAM server to reserve IP
// addresses for the VMs.

// Address or hostname of the IPAM server from which to reserve IP addresses for the cluster machines.
//ipam = "192.168.101.252"

// Token to use to authenticate with the IPAM server.
//ipam_token = "TOKEN_FOR_THE_IPAM_SERVER"


// Set bootstrap_ip, control_plane_ip, and compute_ip if you want to use static
// IPs reserved someone else, rather than the IPAM server.

// The IP address to assign to the bootstrap VM.
//bootstrap_ip = "10.0.0.10"

// The IP addresses to assign to the control plane VMs. The length of this list
// must match the value of control_plane_count.
//control_plane_ips = ["10.0.0.20", "10.0.0.21", "10.0.0.22"]

// The IP addresses to assign to the compute VMs. The length of this list must
// match the value of compute_count.
//compute_ips = ["10.0.0.30", "10.0.0.31", "10.0.0.32"]
bootstrap_ip = "192.168.101.100"
control_plane_ips = ["192.168.101.101", "192.168.101.102", "192.168.101.103"]
compute_ips = ["192.168.101.104"]
